stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t testapp .
    - docker save testapp > testapp.tar

deploy:
  stage: deploy
  script:
    - echo "Simulate deployment or push to server"
